language: node_js
node_js:
    - 16
cache:
  directories:
    - node_modules
    - .next/cache
branches:
  only:
  - main
install:
    - npm i
script:
    # Build app
    - npm run build

after_success:
    # Zip for publishing to github releases
    - zip -r build.zip .next public package.json next.config.js
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key: "$SECRET_ACCESS_KEY"
  zip_file: "build.zip"
  region: "ap-southeast-2"
  app: "courseReview"
  env: "Coursereview-env"
  bucket: "elasticbeanstalk-ap-southeast-2-230008172240"
  on:
    branch: main